-- Ensure table exists (Idempotent)
create table if not exists public.teacher_attendance (
    id bigint generated by default as identity primary key,
    teacher_id bigint not null, -- Assuming teachers table exists with bigint ID
    date date not null,
    check_in_time timestamp with time zone default now(),
    status text default 'Pending',
    rejection_reason text,
    approved_at timestamp with time zone,
    created_at timestamp with time zone default now()
);

-- Enable RLS (best practice, even if policies are open for now)
alter table public.teacher_attendance enable row level security;

-- Policies
-- Drop to ensure we can re-create cleanly (idempotent)
drop policy if exists "Allow read access for authenticated users" on public.teacher_attendance;
drop policy if exists "Allow insert access for authenticated users" on public.teacher_attendance;
drop policy if exists "Allow update access for authenticated users" on public.teacher_attendance;

-- 1. Read: Allow all authenticated users (Admins + Teachers) to read
create policy "Allow read access for authenticated users"
on public.teacher_attendance for select
to authenticated
using (true);

-- 2. Insert: Allow authenticated users to insert (Teachers checking in)
create policy "Allow insert access for authenticated users"
on public.teacher_attendance for insert
to authenticated
with check (true);

-- 3. Update: Allow authenticated users to update (Admins approving)
create policy "Allow update access for authenticated users"
on public.teacher_attendance for update
to authenticated
using (true);

-- ============================================================
-- THE FIX: Enable Realtime for this table
-- ============================================================
-- We check if it's already in the publication to avoid errors, though "add table" is usually safe to run?
-- Actually, simple "alter publication add table" throws error if already exists.

DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.teacher_attendance;
    EXCEPTION
        WHEN duplicate_object THEN
            NULL; -- Already a member, safely ignore
        WHEN OTHERS THEN
            RAISE NOTICE 'Error adding to publication: %', SQLERRM;
    END;
END $$;
