services:
  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: school-app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: school_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: school-app-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: school-app-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
