import { Router } from 'express';
import authRoutes from './auth.routes';
import onboardingRoutes from './onboarding.routes';
import userRoutes from './user.routes';
import schoolRoutes from './school.routes';
import inviteRoutes from './invite.routes';
import studentRoutes from './student.routes';
import teacherRoutes from './teacher.routes';
import feeRoutes from './fee.routes';
import busRoutes from './bus.routes';
import dashboardRoutes from './dashboard.routes';
import classRoutes from './class.routes';
import parentRoutes from './parent.routes';
import noticeRoutes from './notice.routes';
import attendanceRoutes from './attendance.routes';
import notificationRoutes from './notification.routes';
import reportCardRoutes from './reportCard.routes';
import assignmentRoutes from './assignment.routes';
import examRoutes from './exam.routes';
import lessonPlanRoutes from './lessonPlan.routes';
import forumRoutes from './forum.routes';
import transactionRoutes from './transaction.routes';
import timetableRoutes from './timetable.routes';
import quizRoutes from './quiz.routes';
import virtualClassRoutes from './virtual-class.routes';
import academicRoutes from './academic.routes';
import resourceRoutes from './resource.routes';
import externalExamRoutes from './externalExam.routes';
import studentReportRoutes from './studentReport.routes';
import aiRoutes from './ai.routes';
import branchRoutes from './branch.routes';
import subjectRoutes from './subject.routes';
import mediaRoutes from './media.routes';
import emergencyRoutes from './emergency.routes';
import galleryRoutes from './gallery.routes';
import calendarRoutes from './calendar.routes';
import auditRoutes from './audit.routes';
import governanceRoutes from './governance.routes';
import healthRoutes from './health.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/schools', onboardingRoutes);  // /api/schools/onboard — public signup
router.use('/users', userRoutes);
router.use('/schools', schoolRoutes);
router.use('/students', studentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/fees', feeRoutes);
router.use('/buses', busRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/classes', classRoutes);
router.use('/subjects', subjectRoutes);
router.use('/parents', parentRoutes);
router.use('/notices', noticeRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/notifications', notificationRoutes);
router.use('/report-cards', reportCardRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/exams', examRoutes);
router.use('/quizzes', quizRoutes);
router.use('/lesson-plans', lessonPlanRoutes);
router.use('/forum', forumRoutes);
router.use('/transactions', transactionRoutes);
router.use('/timetable', timetableRoutes);
router.use('/virtual-classes', virtualClassRoutes);
router.use('/academic', academicRoutes);
router.use('/external-exams', externalExamRoutes);
router.use('/resources', resourceRoutes);
router.use('/student-reports', studentReportRoutes);
router.use('/ai', aiRoutes);
router.use('/branches', branchRoutes);
router.use('/media', mediaRoutes);
router.use('/emergency', emergencyRoutes);
router.use('/gallery', galleryRoutes);
router.use('/calendar', calendarRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/governance', governanceRoutes);
router.use('/health-logs', healthRoutes);

router.use('/', inviteRoutes);

export default router;
