-- Phase 9: Step 13 Inspector / Ministry Module

-- 1. Inspections Table
CREATE TABLE IF NOT EXISTS public.inspections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    inspector_id UUID REFERENCES auth.users(id),
    curriculum_id UUID REFERENCES public.curricula(id),
    status TEXT NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'In Progress', 'Review', 'Completed', 'Cancelled')),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    overall_score INTEGER CHECK (overall_score BETWEEN 0 AND 100),
    summary_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Defensive Updates (In case table already existed from a previous step)
ALTER TABLE public.inspections ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE;
ALTER TABLE public.inspections ADD COLUMN IF NOT EXISTS inspector_id UUID REFERENCES auth.users(id);
ALTER TABLE public.inspections ADD COLUMN IF NOT EXISTS curriculum_id UUID REFERENCES public.curricula(id);

-- 2. Inspection Checklists (The actual audit items)
CREATE TABLE IF NOT EXISTS public.inspection_checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id UUID REFERENCES public.inspections(id) ON DELETE CASCADE,
    category TEXT NOT NULL CHECK (category IN ('Facilities', 'Curriculum', 'Safety', 'Admin', 'Staffing')),
    item_text TEXT NOT NULL,
    is_compliant BOOLEAN DEFAULT FALSE,
    evidence_url TEXT, -- URL to image/document uploaded by inspector
    comments TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.inspection_checklists ADD COLUMN IF NOT EXISTS inspection_id UUID REFERENCES public.inspections(id) ON DELETE CASCADE;

-- 3. Inspection Signatures (Official Sign-offs)
CREATE TABLE IF NOT EXISTS public.inspection_signatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_id UUID REFERENCES public.inspections(id) ON DELETE CASCADE,
    signer_role TEXT NOT NULL CHECK (signer_role IN ('Inspector', 'Principal', 'Admin', 'Ministry Rep')),
    signer_name TEXT NOT NULL,
    signature_svg TEXT, -- Base64 or SVG data of the signature
    signed_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.inspection_signatures ADD COLUMN IF NOT EXISTS inspection_id UUID REFERENCES public.inspections(id) ON DELETE CASCADE;

-- Enable RLS
ALTER TABLE public.inspections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspection_checklists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inspection_signatures ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DO $$ 
BEGIN
    -- Inspectors can manage their own inspections
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Inspectors can manage their own inspections') THEN
        CREATE POLICY "Inspectors can manage their own inspections" 
        ON public.inspections FOR ALL 
        USING (auth.uid() = inspector_id);
    END IF;

    -- School Admins can view inspections of their school
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'School admins can view their school inspections') THEN
        CREATE POLICY "School admins can view their school inspections" 
        ON public.inspections FOR SELECT 
        USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = inspections.school_id));
    END IF;

    -- Checklist Items visibility
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Visibility of inspection details') THEN
        CREATE POLICY "Visibility of inspection details" 
        ON public.inspection_checklists FOR ALL 
        USING (inspection_id IN (SELECT id FROM public.inspections));
    END IF;

    -- Signature visibility
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Visibility of inspection signatures') THEN
        CREATE POLICY "Visibility of inspection signatures" 
        ON public.inspection_signatures FOR ALL 
        USING (inspection_id IN (SELECT id FROM public.inspections));
    END IF;
END $$;
