-- Phase 9: Step 14 Compliance Dashboard

-- 1. Compliance Snapshots (Historical Data)
CREATE TABLE IF NOT EXISTS public.compliance_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    overall_score INTEGER CHECK (overall_score BETWEEN 0 AND 100),
    facilities_score INTEGER CHECK (facilities_score BETWEEN 0 AND 100),
    safety_health_score INTEGER CHECK (safety_health_score BETWEEN 0 AND 100),
    safeguarding_score INTEGER CHECK (safeguarding_score BETWEEN 0 AND 100),
    snapshot_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.compliance_snapshots ENABLE ROW LEVEL SECURITY;

-- RLS Policy
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'School staff can see their compliance snapshots') THEN
        CREATE POLICY "School staff can see their compliance snapshots" 
        ON public.compliance_snapshots FOR SELECT 
        USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = compliance_snapshots.school_id));
    END IF;
END $$;

-- 2. Compliance Scoring Logic (Convenience View)
-- Note: This is an aggregation view to simplify frontend fetching
CREATE OR REPLACE VIEW public.vw_compliance_metrics AS 
SELECT 
    s.id as school_id,
    -- Facilities Score: % Functional
    COALESCE((
        SELECT (COUNT(CASE WHEN status = 'Functional' THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0))::INTEGER 
        FROM public.facility_registers f 
        WHERE f.school_id = s.id
    ), 0) as facilities_score,
    -- Equipment Score: % Non-Poor/Needs Replacement
    COALESCE((
        SELECT (COUNT(CASE WHEN condition IN ('New', 'Good', 'Fair') THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0))::INTEGER 
        FROM public.equipment_tracking e 
        WHERE e.school_id = s.id
    ), 0) as equipment_score,
    -- Safety Score: % Successful Drills
    COALESCE((
        SELECT (COUNT(CASE WHEN successful = TRUE THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0))::INTEGER 
        FROM public.emergency_drills d 
        WHERE d.school_id = s.id
    ), 0) as safety_score,
    -- Safeguarding Score: % Active Policies
    COALESCE((
        SELECT (COUNT(CASE WHEN status = 'Active' THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0))::INTEGER 
        FROM public.safeguarding_policies p 
        WHERE p.school_id = s.id
    ), 0) as safeguarding_score
FROM public.schools s;
