-- Phase 10: Step 10 Refinement - Enhanced Exam Management

-- 1. Update exams table
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='exams' AND column_name='curriculum_type') THEN
        ALTER TABLE public.exams ADD COLUMN curriculum_type TEXT DEFAULT 'General' CHECK (curriculum_type IN ('Nigerian', 'British', 'Dual', 'General'));
    END IF;
END $$;

-- 2. Update academic_records table
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='academic_records' AND column_name='curriculum_type') THEN
        ALTER TABLE public.academic_records ADD COLUMN curriculum_type TEXT DEFAULT 'General' CHECK (curriculum_type IN ('Nigerian', 'British', 'Dual', 'General'));
    END IF;
END $$;

-- 3. Seed Exam Bodies
CREATE TABLE IF NOT EXISTS public.exam_bodies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    code TEXT UNIQUE NOT NULL,
    curriculum_type TEXT CHECK (curriculum_type IN ('Nigerian', 'British', 'Dual')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.exam_bodies (name, code, curriculum_type)
VALUES 
    ('West African Examinations Council', 'WAEC', 'Nigerian'),
    ('National Examinations Council', 'NECO', 'Nigerian'),
    ('Cambridge Assessment International Education', 'CAMBRIDGE', 'British'),
    ('Pearson Edexcel', 'EDEXCEL', 'British')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, curriculum_type = EXCLUDED.curriculum_type;

-- 4. Exam Candidates Table
CREATE TABLE IF NOT EXISTS public.exam_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES public.students(id),
    exam_body_id UUID REFERENCES public.exam_bodies(id),
    registration_number TEXT,
    status TEXT DEFAULT 'Registered' CHECK (status IN ('Registered', 'Withdrawn', 'Completed')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(student_id, exam_body_id)
);

-- Enable RLS
ALTER TABLE public.exam_bodies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_candidates ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public can see exam bodies') THEN
        CREATE POLICY "Public can see exam bodies" ON public.exam_bodies FOR SELECT USING (TRUE);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'School staff can manage candidates') THEN
        CREATE POLICY "School staff can manage candidates" 
        ON public.exam_candidates FOR ALL 
        USING (student_id IN (SELECT id FROM public.students));
    END IF;
END $$;
