-- Reset: Drop table if exists to avoid conflicts
DROP TABLE IF EXISTS cbt_submissions CASCADE;

-- Create cbt_submissions table
-- FIXED: cbt_exam_id is UUID to match cbt_exams.id
CREATE TABLE cbt_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cbt_exam_id UUID REFERENCES cbt_exams(id) ON DELETE CASCADE,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  score NUMERIC NOT NULL DEFAULT 0,
  answers JSONB DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'Graded',
  submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE cbt_submissions ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- 1. Students see/insert own submissions
CREATE POLICY "Students see own submissions" ON cbt_submissions
FOR SELECT TO authenticated
USING (
  student_id IN (
    SELECT id FROM students WHERE user_id = auth.uid()
  )
);

CREATE POLICY "Students insert own submissions" ON cbt_submissions
FOR INSERT TO authenticated
WITH CHECK (
  student_id IN (
    SELECT id FROM students WHERE user_id = auth.uid()
  )
);

-- 2. Teachers view submissions for their exams
-- We join with cbt_exams (UUID) and teachers (BIGINT)
-- And verify teacher's email matches JWT email
-- 2. Teachers view submissions for their exams
-- Linking via cbt_exams -> teacher_id -> teachers.email = auth.jwt.email
CREATE POLICY "Teachers view submissions for their exams" ON cbt_submissions
FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM cbt_exams
    JOIN teachers ON cbt_exams.teacher_id::text = teachers.id::text -- Safe cast
    WHERE cbt_exams.id = cbt_submissions.cbt_exam_id
    AND lower(teachers.email) = lower(auth.jwt() ->> 'email')
  )
);

-- 3. Admins view all submissions
CREATE POLICY "Admins view all submissions" ON cbt_submissions
FOR SELECT TO authenticated
USING (
  (SELECT role FROM users WHERE email = (auth.jwt() ->> 'email') LIMIT 1) = 'admin'
  OR 
  (auth.jwt() ->> 'email') LIKE '%@admin.com'
);

GRANT ALL ON cbt_submissions TO authenticated;
GRANT ALL ON cbt_submissions TO service_role;
