-- 0041_create_academic_performance.sql
-- This table stores PUBLISHED grades that are visible to Parents/Students/Admins
-- Teachers save to report_cards (Draft or Published)
-- When Published, data syncs here for dashboard visibility

CREATE TABLE IF NOT EXISTS academic_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    term TEXT NOT NULL,
    session TEXT NOT NULL DEFAULT '2023/2024',
    score NUMERIC NOT NULL DEFAULT 0,
    grade TEXT,
    remark TEXT,
    ca_score INTEGER DEFAULT 0,
    exam_score INTEGER DEFAULT 0,
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(student_id, subject, term, session)
);

-- Enable RLS
ALTER TABLE academic_performance ENABLE ROW LEVEL SECURITY;

-- Policies: Anyone authenticated can read (for Parent/Student/Admin dashboards)
DROP POLICY IF EXISTS "Anyone can read academic performance" ON academic_performance;
CREATE POLICY "Anyone can read academic performance" 
ON academic_performance FOR SELECT 
TO authenticated 
USING (true);

-- Only teachers/admins can insert/update (via backend sync from report_cards)
DROP POLICY IF EXISTS "Service role can modify academic performance" ON academic_performance;
CREATE POLICY "Service role can modify academic performance" 
ON academic_performance FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);

-- Grant permissions
GRANT ALL ON academic_performance TO authenticated;
GRANT ALL ON academic_performance TO service_role;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_academic_performance_student 
ON academic_performance(student_id, term, session);
