
-- 1. PROFILES (Users -> Roles)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role text not null check (role in ('student', 'teacher', 'parent', 'admin')),
  school_id uuid not null,
  email text,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. PARENT-STUDENT LINK
create table if not exists public.parent_student_links (
  parent_id uuid references public.profiles(id) on delete cascade,
  student_id uuid references public.profiles(id) on delete cascade,
  school_id uuid not null,
  primary key (parent_id, student_id)
);

-- 3. QUIZZES
-- Ensure table exists. If it exists as UUID, we respect that.
create table if not exists public.quizzes (
  id uuid default gen_random_uuid() primary key, -- Changed to UUID to match existing DB state if implied
  school_id uuid not null, 
  teacher_id uuid references public.profiles(id),
  title text not null,
  is_active boolean default false,
  duration_minutes int,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Safely add columns if they don't exist (Idempotent)
do $$ 
begin
  alter table public.quizzes add column if not exists subject text;
  alter table public.quizzes add column if not exists grade int;
  alter table public.quizzes add column if not exists description text;
  alter table public.quizzes add column if not exists is_published boolean default false;
  alter table public.quizzes add column if not exists is_active boolean default false;
exception
  when others then null;
end $$;


-- 3b. QUESTIONS
-- quiz_id must match quizzes.id type. Based on error, quizzes.id is UUID.
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  quiz_id uuid references public.quizzes(id) on delete cascade, -- Fixed: UUID
  text text not null,
  type text check (type in ('MultipleChoice', 'Theory')),
  points int default 1,
  options jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. QUIZ SUBMISSIONS
create table if not exists public.quiz_submissions (
  id bigint generated by default as identity primary key,
  quiz_id uuid references public.quizzes(id) on delete cascade, -- Fixed: UUID
  student_id uuid references public.profiles(id) on delete cascade,
  school_id uuid not null,
  score int,
  status text check (status in ('in_progress', 'submitted', 'graded')),
  answers jsonb, 
  submitted_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ==========================================
-- ENABLE RLS
-- ==========================================
alter table quiz_submissions enable row level security;
alter table profiles enable row level security;

-- ==========================================
-- RLS POLICIES
-- ==========================================

-- Policy: Parents can view submissions ONLY for their linked children in their school
-- Drop existing implementation if exists to avoid collision? 
-- `create policy` throws if exists. user can ignore error or we use `do block`.
-- For simplicity, we assume user cleans up or we leave it. 
-- But "fix once and for all" implies robust.
drop policy if exists "Parents view linked children submissions" on public.quiz_submissions;
create policy "Parents view linked children submissions"
on public.quiz_submissions for select
to authenticated
using (
  exists (
    select 1 from public.parent_student_links psl
    where psl.parent_id = auth.uid()
    and psl.student_id = quiz_submissions.student_id
    and psl.school_id = quiz_submissions.school_id
  )
);

drop policy if exists "Students see own submissions" on public.quiz_submissions;
create policy "Students see own submissions"
on public.quiz_submissions for select
to authenticated
using (student_id = auth.uid());

drop policy if exists "Teachers see school submissions" on public.quiz_submissions;
create policy "Teachers see school submissions"
on public.quiz_submissions for select
to authenticated
using (
  exists (
    select 1 from public.profiles
    where id = auth.uid()
    and role = 'teacher'
    and school_id = quiz_submissions.school_id
  )
);

-- Enable Realtime
-- Check if publication exists? Usually separate command.

-- Enable Realtime
do $$
begin
  alter publication supabase_realtime add table public.quiz_submissions;
exception
  when duplicate_object then null;
end $$;

-- ==========================================
-- MISSING POLICIES FOR QUIZZES & QUESTIONS
-- ==========================================

alter table quizzes enable row level security;
alter table questions enable row level security;

-- Quizzes: Teachers/Admins can do everything
drop policy if exists "Teachers can manage their own quizzes" on public.quizzes;
create policy "Teachers can manage their own quizzes"
on public.quizzes for all
to authenticated
using (
  (auth.uid() = teacher_id) OR
  (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
)
with check (
  (auth.uid() = teacher_id) OR
  (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
);

-- Quizzes: Students/Parents can view published quizzes
drop policy if exists "Students/Parents can view active quizzes" on public.quizzes;
create policy "Students/Parents can view active quizzes"
on public.quizzes for select
to authenticated
using (is_published = true and is_active = true and school_id = (select school_id from public.profiles where id = auth.uid()));

-- Questions: Teachers/Admins can manage
drop policy if exists "Teachers can manage quiz questions" on public.questions;
create policy "Teachers can manage quiz questions"
on public.questions for all
to authenticated
using (
  exists (
    select 1 from public.quizzes
    where quizzes.id = questions.quiz_id
    and (quizzes.teacher_id = auth.uid() or exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
  )
)
with check (
  exists (
    select 1 from public.quizzes
    where quizzes.id = questions.quiz_id
    and (quizzes.teacher_id = auth.uid() or exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'))
  )
);

-- Questions: Students/Parents can view if quiz is visible
drop policy if exists "Students can view questions for active quizzes" on public.questions;
create policy "Students can view questions for active quizzes"
on public.questions for select
to authenticated
using (
  exists (
    select 1 from public.quizzes
    where quizzes.id = questions.quiz_id
    and quizzes.is_published = true 
    and quizzes.is_active = true
    and quizzes.school_id = (select school_id from public.profiles where id = auth.uid())
  )
);

