-- PRODUCTION SETUP & REPAIR SCRIPT
-- Consolidates 0016, 0017, and 0018 to ensure full backend readiness.
-- Run this in Supabase SQL Editor to fix missing tables or 500 errors.

BEGIN;

-- ============================================================================
-- 1. CORE INFRASTRUCTURE (From 0016)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.schools (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    address TEXT,
    state TEXT,
    lga TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    logo_url TEXT,
    established_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    curriculum_type TEXT,
    principal_signature TEXT
);

-- Ensure profiles has school_id
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id);
CREATE INDEX IF NOT EXISTS idx_profiles_school_id ON public.profiles(school_id);

-- ============================================================================
-- 2. FACILITIES & COMPLIANCE (From 0016 - Fixes 500 Errors)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.facility_registers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    capacity INTEGER DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Functional',
    last_inspected_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.facility_registers ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.compliance_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    overall_score INTEGER,
    facilities_score INTEGER,
    safety_health_score INTEGER,
    safeguarding_score INTEGER,
    snapshot_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.compliance_snapshots ENABLE ROW LEVEL SECURITY;

-- Re-apply policies safely
DROP POLICY IF EXISTS "Users can see their own school facilities" ON public.facility_registers;
CREATE POLICY "Users can see their own school facilities" 
ON public.facility_registers FOR SELECT 
USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = facility_registers.school_id));

DROP POLICY IF EXISTS "School staff can see their compliance snapshots" ON public.compliance_snapshots;
CREATE POLICY "School staff can see their compliance snapshots" 
ON public.compliance_snapshots FOR SELECT 
USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = compliance_snapshots.school_id));

-- ============================================================================
-- 3. EXAM RESULTS (From 0017)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.exam_results (
    id SERIAL PRIMARY KEY,
    student_id INTEGER REFERENCES public.students(id) ON DELETE CASCADE,
    exam_id INTEGER,
    class_id INTEGER,
    teacher_id INTEGER,
    ca_score DECIMAL(5,2),
    exam_score DECIMAL(5,2),
    total_score DECIMAL(5,2),
    grade TEXT,
    curriculum_type TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS curriculum_type TEXT;

-- ============================================================================
-- 4. INSPECTOR PORTAL (From 0018 - Final)
-- ============================================================================
-- Ensure tables exist (DDL is idempotent-ish if we check existence, but simpler to use IF NOT EXISTS logic where possible or rely on the previous master_migration)
-- Re-running the CREATE TABLE IF NOT EXISTS for Inspector Portal:

CREATE TABLE IF NOT EXISTS public.inspectors (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    inspector_code TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    ministry_department TEXT,
    region TEXT,
    contact_email TEXT UNIQUE NOT NULL,
    contact_phone TEXT,
    digital_signature TEXT,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inspection_checklist_templates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    questions JSONB NOT NULL,
    scoring_rubric JSONB,
    version TEXT DEFAULT '1.0',
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================================
-- 5. FUNCTION & TRIGGERS
-- ============================================================================
-- Add any critical functions here if missing.

COMMIT;

SELECT '✅ Production Setup Completed. All systems should be ready.' as status;
