-- ============================================
-- MIGRATION: Phase 1 Completion (Fees, Roles, Broadcasts)
-- Purpose: Add missing tables for MVP completion
-- ============================================

-- 1. UPDATE VALID ROLES
-- We need to drop the existing check constraint and add the new one including 'principal' and 'counselor'
DO $$ 
BEGIN
  -- Drop constraint if exists (name might vary, so we try to catch it or look it up)
  -- The standard naming for a check constraint on column 'role' in table 'profiles' is usually 'profiles_role_check'
  ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
  
  -- Add new constraint
  ALTER TABLE profiles ADD CONSTRAINT profiles_role_check 
    CHECK (role IN ('student', 'teacher', 'parent', 'admin', 'principal', 'counselor'));
END $$;


-- 2. CREATE FEES TABLE
CREATE TABLE IF NOT EXISTS fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER REFERENCES students(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL, -- e.g. "Term 2 Tuition", "Bus Fee"
  description TEXT,
  amount DECIMAL(12,2) NOT NULL,
  due_date DATE NOT NULL,
  status TEXT CHECK (status IN ('pending', 'partial', 'paid', 'overdue')) DEFAULT 'pending',
  paid_amount DECIMAL(12,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Fees
ALTER TABLE fees ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins/Principals can manage fees" ON fees;
CREATE POLICY "Admins/Principals can manage fees" ON fees
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'principal'))
  );

DROP POLICY IF EXISTS "Parents can view their children's fees" ON fees;
CREATE POLICY "Parents can view their children's fees" ON fees
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM parent_children pc
      JOIN profiles p ON p.parent_id = pc.parent_id
      WHERE pc.student_id = fees.student_id AND p.id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Students can view their own fees" ON fees;
CREATE POLICY "Students can view their own fees" ON fees
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND student_id = fees.student_id
    )
  );


-- 3. CREATE TRANSACTIONS TABLE (for Payment History)
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fee_id BIGINT REFERENCES fees(id) ON DELETE SET NULL,
  student_id INTEGER REFERENCES students(id) ON DELETE CASCADE,
  payer_id UUID REFERENCES auth.users(id), -- The user who made the payment (usually parent)
  amount DECIMAL(12,2) NOT NULL,
  reference TEXT UNIQUE NOT NULL, -- Payment Gateway Reference
  provider TEXT NOT NULL, -- 'paystack', 'flutterwave', 'cash', 'bank_transfer'
  status TEXT CHECK (status IN ('pending', 'success', 'failed')) DEFAULT 'pending',
  metadata JSONB, -- Store full gateway response
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Transactions
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins/Principals can view all transactions" ON transactions;
CREATE POLICY "Admins/Principals can view all transactions" ON transactions
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'principal'))
  );

DROP POLICY IF EXISTS "Users can view their own transactions" ON transactions;
CREATE POLICY "Users can view their own transactions" ON transactions
  FOR SELECT TO authenticated
  USING (payer_id = auth.uid());


-- 4. EMERGENCY BROADCASTS LOG
CREATE TABLE IF NOT EXISTS emergency_broadcasts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES auth.users(id),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  audience TEXT CHECK (audience IN ('all', 'parents', 'teachers', 'staff')),
  channels JSONB, -- e.g. ["push", "email", "sms"]
  delivery_stats JSONB DEFAULT '{"sent": 0, "failed": 0}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE emergency_broadcasts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Only Admins/Principals can send broadcasts" ON emergency_broadcasts;
CREATE POLICY "Only Admins/Principals can send broadcasts" ON emergency_broadcasts
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'principal'))
  );

DROP POLICY IF EXISTS "Recipients can view broadcasts" ON emergency_broadcasts;
CREATE POLICY "Recipients can view broadcasts" ON emergency_broadcasts
  FOR SELECT TO authenticated
  USING (true); -- Public read for authenticated users (it's a broadcast)


-- 5. ABSENCE EXPLANATIONS (Parent Two-Way Logic)
CREATE TABLE IF NOT EXISTS absence_explanations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_id BIGINT REFERENCES student_attendance(id) ON DELETE CASCADE,
  parent_id INTEGER REFERENCES parents(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  category TEXT CHECK (category IN ('sick', 'family_emergency', 'religious', 'other')),
  status TEXT CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
  admin_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE absence_explanations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Parents can create explanations for their kids" ON absence_explanations;
CREATE POLICY "Parents can create explanations for their kids" ON absence_explanations
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM student_attendance sa
      JOIN parent_children pc ON pc.student_id = sa.student_id
      JOIN profiles p ON p.parent_id = pc.parent_id
      WHERE sa.id = absence_explanations.attendance_id AND p.id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Admins/Principals/Teachers can manage explanations" ON absence_explanations;
CREATE POLICY "Admins/Principals/Teachers can manage explanations" ON absence_explanations
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'principal', 'teacher'))
  );

DROP POLICY IF EXISTS "Parents can view own explanations" ON absence_explanations;
CREATE POLICY "Parents can view own explanations" ON absence_explanations
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles WHERE id = auth.uid() AND parent_id = absence_explanations.parent_id
    )
  );
