-- Phase 8: Step 11 Infrastructure & Facilities Log

-- 1. Facility Register (Classrooms, Labs, Toilets, Library, Sick bay)
CREATE TABLE IF NOT EXISTS public.facility_registers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Classroom', 'Laboratory', 'Toilet', 'Library', 'Sick bay', 'Staff Room', 'Other')),
    capacity INTEGER DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Functional' CHECK (status IN ('Functional', 'Maintenance', 'Out of Order')),
    last_inspected_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.facility_registers ENABLE ROW LEVEL SECURITY;

-- 2. Equipment Tracking (Computers, Fire Extinguishers, Lab Kits, etc.)
CREATE TABLE IF NOT EXISTS public.equipment_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    facility_id BIGINT REFERENCES public.facility_registers(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Computer', 'Science Kit', 'Fire Safety', 'Furniture', 'First Aid', 'Electrical', 'Other')),
    serial_number TEXT,
    condition TEXT NOT NULL DEFAULT 'Good' CHECK (condition IN ('New', 'Good', 'Fair', 'Poor', 'Needs Replacement')),
    purchase_date DATE,
    next_service_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.equipment_tracking ENABLE ROW LEVEL SECURITY;

-- RLS Policies (Assuming school-based isolation)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can see their own school facilities') THEN
        CREATE POLICY "Users can see their own school facilities" 
        ON public.facility_registers FOR SELECT 
        USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = facility_registers.school_id));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can see their own school equipment') THEN
        CREATE POLICY "Users can see their own school equipment" 
        ON public.equipment_tracking FOR SELECT 
        USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = equipment_tracking.school_id));
    END IF;
END $$;
