-- Phase 8: Step 12 Health, Safety & Child Protection

-- 1. Health & Safety Incident Logs
CREATE TABLE IF NOT EXISTS public.health_incident_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES public.students(id) ON DELETE SET NULL,
    incident_type TEXT NOT NULL CHECK (incident_type IN ('Injury', 'Illness', 'Allergy Reaction', 'Behavioral', 'Other')),
    severity TEXT NOT NULL CHECK (severity IN ('Minor', 'Moderate', 'Severe', 'Critical')),
    description TEXT NOT NULL,
    action_taken TEXT,
    notified_parent BOOLEAN DEFAULT FALSE,
    notified_by UUID REFERENCES auth.users(id),
    location TEXT,
    incident_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Emergency Drills (Fire, Lockdown, etc.)
CREATE TABLE IF NOT EXISTS public.emergency_drills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    drill_type TEXT NOT NULL CHECK (drill_type IN ('Fire', 'Lockdown', 'Earthquake', 'Medical Emergency')),
    drill_date DATE NOT NULL DEFAULT CURRENT_DATE,
    duration_minutes INTEGER,
    participants_count INTEGER,
    successful BOOLEAN DEFAULT TRUE,
    notes TEXT,
    conducted_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Safeguarding & Child Protection Policies
CREATE TABLE IF NOT EXISTS public.safeguarding_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    file_url TEXT NOT NULL,
    version TEXT,
    effective_date DATE,
    expiry_date DATE,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Draft', 'Archived')),
    uploaded_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.health_incident_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_drills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safeguarding_policies ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DO $$ 
BEGIN
    -- Health Logs
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'School staff can see their health logs') THEN
        CREATE POLICY "School staff can see their health logs" 
        ON public.health_incident_logs FOR ALL 
        USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = health_incident_logs.school_id));
    END IF;

    -- Emergency Drills
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'School staff can see their drills') THEN
        CREATE POLICY "School staff can see their drills" 
        ON public.emergency_drills FOR ALL 
        USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = emergency_drills.school_id));
    END IF;

    -- Safeguarding Policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'School staff can see their policies') THEN
        CREATE POLICY "School staff can see their policies" 
        ON public.safeguarding_policies FOR ALL 
        USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = safeguarding_policies.school_id));
    END IF;
END $$;
