-- ============================================================================
-- � PART 1: CORE INFRASTRUCTURE (Run First)
-- ============================================================================

-- 1. Ensure Schools table exists (Base for multi-tenancy)
CREATE TABLE IF NOT EXISTS public.schools (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    address TEXT,
    state TEXT,
    lga TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    logo_url TEXT,
    established_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Fix: school_documents table might have a NOT NULL constraint on file_url 
-- which blocks the auto-generator trigger.
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'school_documents') THEN
        ALTER TABLE public.school_documents ALTER COLUMN file_url DROP NOT NULL;
    END IF;
END $$;

-- 2. Standardize the Profiles Table
-- Ensure school_id exists so policies can verify tenant access.
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id);
CREATE INDEX IF NOT EXISTS idx_profiles_school_id ON public.profiles(school_id);

-- ============================================================================
-- 🚀 PART 2: GOVERNANCE TABLES & COLUMNS
-- ============================================================================

-- 3. Facility & Equipment (Phase 8, Step 11)
CREATE TABLE IF NOT EXISTS public.facility_registers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Classroom', 'Laboratory', 'Toilet', 'Library', 'Sick bay', 'Staff Room', 'Other')),
    capacity INTEGER DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Functional' CHECK (status IN ('Functional', 'Maintenance', 'Out of Order')),
    last_inspected_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.facility_registers ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS public.equipment_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    facility_id BIGINT REFERENCES public.facility_registers(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Computer', 'Science Kit', 'Fire Safety', 'Furniture', 'First Aid', 'Electrical', 'Other')),
    serial_number TEXT,
    condition TEXT NOT NULL DEFAULT 'Good' CHECK (condition IN ('New', 'Good', 'Fair', 'Poor', 'Needs Replacement')),
    purchase_date DATE,
    next_service_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.equipment_tracking ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE;

-- 4. Health, Safety & Safeguarding (Phase 8, Step 12)
CREATE TABLE IF NOT EXISTS public.health_incident_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES public.students(id) ON DELETE SET NULL,
    incident_type TEXT NOT NULL CHECK (incident_type IN ('Injury', 'Illness', 'Allergy Reaction', 'Behavioral', 'Other')),
    severity TEXT NOT NULL CHECK (severity IN ('Minor', 'Moderate', 'Severe', 'Critical')),
    description TEXT NOT NULL,
    action_taken TEXT,
    notified_parent BOOLEAN DEFAULT FALSE,
    notified_by UUID REFERENCES auth.users(id),
    location TEXT,
    incident_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.health_incident_logs ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS public.emergency_drills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    drill_type TEXT NOT NULL CHECK (drill_type IN ('Fire', 'Lockdown', 'Earthquake', 'Medical Emergency')),
    drill_date DATE NOT NULL DEFAULT CURRENT_DATE,
    duration_minutes INTEGER,
    participants_count INTEGER,
    successful BOOLEAN DEFAULT TRUE,
    notes TEXT,
    conducted_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.emergency_drills ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE;
ALTER TABLE public.emergency_drills ADD COLUMN IF NOT EXISTS successful BOOLEAN DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS public.safeguarding_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    file_url TEXT NOT NULL,
    version TEXT,
    effective_date DATE,
    expiry_date DATE,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Draft', 'Archived')),
    uploaded_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.safeguarding_policies ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE;

-- 5. Inspection & Compliance (Phase 9, Steps 13 & 14)
CREATE TABLE IF NOT EXISTS public.inspections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    inspector_id UUID REFERENCES auth.users(id),
    curriculum_id UUID REFERENCES public.curricula(id),
    status TEXT NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'In Progress', 'Review', 'Completed', 'Cancelled')),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    overall_score INTEGER CHECK (overall_score BETWEEN 0 AND 100),
    summary_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.inspections ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE;
ALTER TABLE public.inspections ADD COLUMN IF NOT EXISTS inspector_id UUID REFERENCES auth.users(id);
ALTER TABLE public.inspections ADD COLUMN IF NOT EXISTS curriculum_id UUID REFERENCES public.curricula(id);

CREATE TABLE IF NOT EXISTS public.compliance_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE,
    overall_score INTEGER CHECK (overall_score BETWEEN 0 AND 100),
    facilities_score INTEGER CHECK (facilities_score BETWEEN 0 AND 100),
    safety_health_score INTEGER CHECK (safety_health_score BETWEEN 0 AND 100),
    safeguarding_score INTEGER CHECK (safeguarding_score BETWEEN 0 AND 100),
    snapshot_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.compliance_snapshots ADD COLUMN IF NOT EXISTS school_id UUID REFERENCES public.schools(id) ON DELETE CASCADE;

-- ============================================================================
-- 🚀 PART 3: SECURITY POLICIES (RLS)
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.facility_registers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.health_incident_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_drills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safeguarding_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compliance_snapshots ENABLE ROW LEVEL SECURITY;

-- Apply corrected RLS Policies (Idempotent)
DROP POLICY IF EXISTS "Users can see their own school facilities" ON public.facility_registers;
CREATE POLICY "Users can see their own school facilities" 
ON public.facility_registers FOR SELECT 
USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = facility_registers.school_id));

DROP POLICY IF EXISTS "Users can see their own school equipment" ON public.equipment_tracking;
CREATE POLICY "Users can see their own school equipment" 
ON public.equipment_tracking FOR SELECT 
USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = equipment_tracking.school_id));

DROP POLICY IF EXISTS "School staff can see their health logs" ON public.health_incident_logs;
CREATE POLICY "School staff can see their health logs" 
ON public.health_incident_logs FOR ALL 
USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = health_incident_logs.school_id));

DROP POLICY IF EXISTS "School staff can see their drills" ON public.emergency_drills;
CREATE POLICY "School staff can see their drills" 
ON public.emergency_drills FOR ALL 
USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = emergency_drills.school_id));

DROP POLICY IF EXISTS "School staff can see their policies" ON public.safeguarding_policies;
CREATE POLICY "School staff can see their policies" 
ON public.safeguarding_policies FOR ALL 
USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = safeguarding_policies.school_id));

DROP POLICY IF EXISTS "School staff can see their compliance snapshots" ON public.compliance_snapshots;
CREATE POLICY "School staff can see their compliance snapshots" 
ON public.compliance_snapshots FOR SELECT 
USING (auth.uid() IN (SELECT id FROM public.profiles WHERE school_id = compliance_snapshots.school_id));

-- ============================================================================
-- 🚀 PART 4: DATA BACKFILL
-- ============================================================================

-- 6. Backfill Default School (Required for testing)
INSERT INTO public.schools (name) VALUES ('Default Pilot School') ON CONFLICT DO NOTHING;
UPDATE public.profiles SET school_id = (SELECT id FROM public.schools LIMIT 1) WHERE school_id IS NULL;

SELECT '✅ Unified Backend Fix Applied' as status;
