-- ============================================================================
-- Migration: 0024_consolidated_schema_fixes
-- Purpose: Consolidated schema fixes (replaces 0020-0023 if needed)
-- Created: 2026-01-05
-- Dependencies: 0001_initial_schema.sql
-- ============================================================================
-- This migration combines all schema fixes:
-- - Email columns for students/teachers/parents
-- - student_fees term and title columns
-- - classes table timestamps and structure fix
-- ============================================================================

-- 1. ADD EMAIL COLUMNS
DO $$ 
BEGIN
  -- Students email
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='email') THEN
    ALTER TABLE students ADD COLUMN email TEXT;
    ALTER TABLE students ADD CONSTRAINT students_email_unique UNIQUE (email);
    CREATE INDEX idx_students_email ON students(email);
  END IF;
  
  -- Teachers email
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='teachers' AND column_name='email') THEN
    ALTER TABLE teachers ADD COLUMN email TEXT;
    ALTER TABLE teachers ADD CONSTRAINT teachers_email_unique UNIQUE (email);
    CREATE INDEX idx_teachers_email ON teachers(email);
  END IF;
  
  -- Parents email
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='parents' AND column_name='email') THEN
    ALTER TABLE parents ADD COLUMN email TEXT;
    ALTER TABLE parents ADD CONSTRAINT parents_email_unique UNIQUE (email);
    CREATE INDEX idx_parents_email ON parents(email);
  END IF;
END $$;

-- 2. FIX STUDENT_FEES COLUMNS
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='student_fees' AND column_name='term') THEN
    ALTER TABLE student_fees ADD COLUMN term TEXT;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='student_fees' AND column_name='title') THEN
    ALTER TABLE student_fees ADD COLUMN title TEXT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_student_fees_term ON student_fees(term);

-- 3. FIX CLASSES TABLE
DROP TABLE IF EXISTS classes CASCADE;

CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade INTEGER,
    section TEXT,
    department TEXT,
    subject TEXT,
    student_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_classes_grade ON classes(grade);
CREATE INDEX idx_classes_section ON classes(section);

ALTER TABLE classes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "select_classes_authenticated" ON classes
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "modify_classes_authenticated" ON classes
    FOR ALL USING (auth.role() = 'authenticated');

-- Comments
COMMENT ON TABLE classes IS 'Stores class/section information';
COMMENT ON COLUMN student_fees.term IS 'Academic term';
COMMENT ON COLUMN student_fees.title IS 'Fee title/description';

SELECT '✅ Migration 0024 completed - All schema fixes applied!' as status;

/*
ROLLBACK INSTRUCTIONS:
-- Email columns
ALTER TABLE students DROP COLUMN IF EXISTS email CASCADE;
ALTER TABLE teachers DROP COLUMN IF EXISTS email CASCADE;
ALTER TABLE parents DROP COLUMN IF EXISTS email CASCADE;

-- student_fees columns
ALTER TABLE student_fees DROP COLUMN IF EXISTS term;
ALTER TABLE student_fees DROP COLUMN IF EXISTS title;

-- classes table
DROP TABLE IF EXISTS classes CASCADE;
-- Then re-run 0001_initial_schema.sql
*/
