-- 0040_fix_all_cbt.sql
-- Consolidated fix for CBT Emails, UUIDs, and RLS Policies
-- & SYNC with Parent Dashboard visibility

-- ==========================================
-- PART 1: FIX CBT_EXAMS POLICIES (Type-Safe)
-- ==========================================

ALTER TABLE cbt_exams ENABLE ROW LEVEL SECURITY;

-- Drop potentially broken policies
DROP POLICY IF EXISTS "Auth read cbt" ON cbt_exams;
DROP POLICY IF EXISTS "Teachers can insert their own exams" ON cbt_exams;
DROP POLICY IF EXISTS "Teachers can update their own exams" ON cbt_exams;
DROP POLICY IF EXISTS "Teachers can delete their own exams" ON cbt_exams;

-- Re-create Policies with strictly TEXT casting to prevent "integer = uuid" errors
-- AND using auth.jwt() to avoid accessing restricted auth.users table

CREATE POLICY "Auth read cbt" ON cbt_exams 
FOR SELECT TO authenticated 
USING (true);

CREATE POLICY "Teachers can insert their own exams" ON cbt_exams
FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM teachers 
    WHERE teachers.email = (auth.jwt() ->> 'email')
    AND teachers.id::text = cbt_exams.teacher_id::text
  )
);

CREATE POLICY "Teachers can update their own exams" ON cbt_exams
FOR UPDATE TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM teachers 
    WHERE teachers.email = (auth.jwt() ->> 'email')
    AND teachers.id::text = cbt_exams.teacher_id::text
  )
);

CREATE POLICY "Teachers can delete their own exams" ON cbt_exams
FOR DELETE TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM teachers 
    WHERE teachers.email = (auth.jwt() ->> 'email')
    AND teachers.id::text = cbt_exams.teacher_id::text
  )
);

-- ==========================================
-- PART 2: FIX CBT_SUBMISSIONS TABLE (UUID)
-- ==========================================

DROP TABLE IF EXISTS cbt_submissions CASCADE;

-- Create table using UUID for cbt_exam_id
CREATE TABLE cbt_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cbt_exam_id UUID REFERENCES cbt_exams(id) ON DELETE CASCADE,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  score NUMERIC NOT NULL DEFAULT 0,
  answers JSONB DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'Graded',
  submitted_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE cbt_submissions ENABLE ROW LEVEL SECURITY;

-- Policies for Submissions

-- Students: Use EMAIL lookup instead of user_id to avoid Integer=UUID error if user_id type is ambiguous
CREATE POLICY "Students see own submissions" ON cbt_submissions
FOR SELECT TO authenticated
USING (
  student_id IN (
    SELECT id FROM students WHERE email = (auth.jwt() ->> 'email')
  )
);

CREATE POLICY "Students insert own submissions" ON cbt_submissions
FOR INSERT TO authenticated
WITH CHECK (
  student_id IN (
    SELECT id FROM students WHERE email = (auth.jwt() ->> 'email')
  )
);

CREATE POLICY "Teachers view submissions for their exams" ON cbt_submissions
FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM cbt_exams
    JOIN teachers ON cbt_exams.teacher_id::text = teachers.id::text
    WHERE cbt_exams.id = cbt_submissions.cbt_exam_id
    AND lower(teachers.email) = lower(auth.jwt() ->> 'email')
  )
);

CREATE POLICY "Admins view all submissions" ON cbt_submissions
FOR SELECT TO authenticated
USING (
  (SELECT role FROM users WHERE email = (auth.jwt() ->> 'email') LIMIT 1) = 'admin'
  OR 
  (auth.jwt() ->> 'email') LIKE '%@admin.com'
);

GRANT ALL ON cbt_submissions TO authenticated;
GRANT ALL ON cbt_submissions TO service_role;
