
-- 1. Create 'subjects' table if not exists
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create 'classes' table if not exists
CREATE TABLE IF NOT EXISTS classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2b. FIX: Ensure 'class_name' column exists
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'classes' AND column_name = 'class_name') THEN
        ALTER TABLE classes ADD COLUMN class_name TEXT;
    END IF;
END $$;

-- 2c. Backfill data if needed
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'classes' AND column_name = 'grade') THEN
        UPDATE classes SET class_name = grade::text WHERE class_name IS NULL OR class_name = '';
    END IF;
END $$;

-- 2d. Attempt to add constraint (Best effort, but don't fail script if duplicates exist)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'classes_class_name_key') THEN
        BEGIN
            ALTER TABLE classes ADD CONSTRAINT classes_class_name_key UNIQUE (class_name);
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Skipping Unique Constraint: Duplicates found in classes table.';
        END;
    END IF;
END $$;

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'subjects_name_key') THEN
        BEGIN
            ALTER TABLE subjects ADD CONSTRAINT subjects_name_key UNIQUE (name);
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Skipping Unique Constraint: Duplicates found in subjects table.';
        END;
    END IF;
END $$;

-- 3. Populate with default data using SAFE INSERT (Avoids ON CONFLICT error if constraint missing)

-- Insert Subjects
INSERT INTO subjects (name)
SELECT t.n
FROM unnest(ARRAY['Mathematics', 'English', 'Physics', 'Chemistry', 'Biology', 'History', 'Geography', 'Computer Science', 'Art', 'Music', 'Physical Education']) as t(n)
WHERE NOT EXISTS (SELECT 1 FROM subjects WHERE name = t.n);

-- Insert Classes
INSERT INTO classes (class_name)
SELECT t.c
FROM unnest(ARRAY['Grade 7A', 'Grade 7B', 'Grade 8A', 'Grade 8B', 'Grade 9A', 'Grade 9B', 'Grade 10A', 'Grade 10B', 'Grade 11A', 'Grade 11B', 'Grade 12A', 'Grade 12B']) as t(c)
WHERE NOT EXISTS (SELECT 1 FROM classes WHERE class_name = t.c);

-- 4. Enable RLS and Policies
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN 
    DROP POLICY IF EXISTS "Allow public read subjects" ON subjects;
    CREATE POLICY "Allow public read subjects" ON subjects FOR SELECT USING (true);
    
    DROP POLICY IF EXISTS "Allow public read classes" ON classes;
    CREATE POLICY "Allow public read classes" ON classes FOR SELECT USING (true);
    
    -- Optional Admin write access
    DROP POLICY IF EXISTS "Allow admin insert subjects" ON subjects;
    CREATE POLICY "Allow admin insert subjects" ON subjects FOR INSERT WITH CHECK (auth.role() = 'authenticated');
    
    DROP POLICY IF EXISTS "Allow admin insert classes" ON classes;
    CREATE POLICY "Allow admin insert classes" ON classes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
END $$;
