
-- 0. Safe Fix for ID Column (Strict Force Mode)

-- 1. Enable UUID Extension (required if ID is UUID)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Clean up 'classes' table columns first
ALTER TABLE classes ALTER COLUMN class_name DROP NOT NULL;
ALTER TABLE classes ALTER COLUMN created_at DROP NOT NULL;
-- If legacy columns exist, make them nullable
DO $$ BEGIN 
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'classes' AND column_name = 'subject') THEN
        ALTER TABLE classes ALTER COLUMN "subject" DROP NOT NULL; 
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'classes' AND column_name = 'section') THEN
        ALTER TABLE classes ALTER COLUMN "section" DROP NOT NULL; 
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'classes' AND column_name = 'grade') THEN
        ALTER TABLE classes ALTER COLUMN "grade" DROP NOT NULL; 
    END IF;
END $$;

-- 3. Fix ID Column - The Nuclear Option
-- We check the type. If text, default to uuid. If number, default to sequence.
DO $$ 
DECLARE
    id_type text;
BEGIN 
    SELECT data_type INTO id_type FROM information_schema.columns WHERE table_name = 'classes' AND column_name = 'id';
    
    IF id_type = 'uuid' THEN
         ALTER TABLE classes ALTER COLUMN id SET DEFAULT gen_random_uuid();
    ELSIF id_type = 'integer' OR id_type = 'bigint' THEN
         -- Create sequence if identity fails
         BEGIN
            ALTER TABLE classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
         EXCEPTION WHEN OTHERS THEN
             -- Identity might exist or fail. Fallback to sequence.
             CREATE SEQUENCE IF NOT EXISTS classes_id_seq_fallback;
             -- Unbind existing default if any?
             -- ALTER TABLE classes ALTER COLUMN id DROP DEFAULT; 
             ALTER TABLE classes ALTER COLUMN id SET DEFAULT nextval('classes_id_seq_fallback');
             PERFORM setval('classes_id_seq_fallback', COALESCE((SELECT MAX(id) FROM classes), 0) + 1, false);
         END;
    ELSE
         -- Assume Text
         ALTER TABLE classes ALTER COLUMN id SET DEFAULT gen_random_uuid()::text;
    END IF;
END $$;

-- 4. Constraint
DO $$ BEGIN 
    ALTER TABLE classes DROP CONSTRAINT IF EXISTS classes_class_name_key;
    ALTER TABLE classes ADD CONSTRAINT classes_class_name_key UNIQUE (class_name);
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- 5. Seed Data
INSERT INTO classes (class_name)
SELECT t.c
FROM unnest(ARRAY['Grade 7A', 'Grade 7B', 'Grade 8A', 'Grade 8B', 'Grade 9A', 'Grade 9B', 'Grade 10A', 'Grade 10B', 'Grade 11A', 'Grade 11B', 'Grade 12A', 'Grade 12B']) as t(c)
WHERE NOT EXISTS (SELECT 1 FROM classes WHERE class_name = t.c);
