-- Phase 2 Schema: Teaching & Learning Layer

-- 1. Resources Table (LMS)
CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  type TEXT NOT NULL CHECK (type IN ('PDF', 'Video', 'Slides', 'Audio')),
  subject TEXT NOT NULL,
  grade INTEGER, -- Corresponds to numerical grade level e.g., 10, 11
  url TEXT NOT NULL, -- Supabase Storage URL
  thumbnail_url TEXT,
  language TEXT CHECK (language IN ('English', 'Hausa', 'Yoruba', 'Igbo')) DEFAULT 'English',
  curriculum_tags TEXT[], -- Array of strings for tags like "Term 1", "Week 3"
  teacher_id BIGINT, -- Uploader (nullable, no FK constraint)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_public BOOLEAN DEFAULT TRUE -- Visible to all or just own class
);

-- Enable RLS for resources
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can view public resources
CREATE POLICY "Public resources are viewable by everyone" ON resources
  FOR SELECT USING (is_public = true);

-- Policy: Teachers can insert their own resources
CREATE POLICY "Teachers can insert resources" ON resources
  FOR INSERT WITH CHECK (
    teacher_id IN (SELECT id FROM teachers WHERE user_id = auth.uid())
  );

-- 2. Quizzes Table
CREATE TABLE IF NOT EXISTS quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  subject TEXT NOT NULL,
  grade INTEGER,
  teacher_id BIGINT, -- No FK constraint
  duration_minutes INTEGER,
  is_published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Questions Table
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT, -- No FK constraint, manual reference
  text TEXT NOT NULL,
  type TEXT CHECK (type IN ('MultipleChoice', 'Theory', 'TrueFalse')) NOT NULL,
  options JSONB, -- Array of {id, text, isCorrect}
  points INTEGER DEFAULT 1,
  image_url TEXT
);

-- 4. Quiz Submissions Table
CREATE TABLE IF NOT EXISTS quiz_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT, -- No FK constraint
  student_id BIGINT, -- No FK constraint
  answers JSONB, -- Store student answers: [{questionId, selectedOption}]
  score INTEGER,
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT CHECK (status IN ('Graded', 'Pending')) DEFAULT 'Pending'
);

-- Enable RLS
ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_submissions ENABLE ROW LEVEL SECURITY;

-- Policies for Quizzes
CREATE POLICY "Everyone can view published quizzes" ON quizzes
  FOR SELECT USING (is_published = true);

CREATE POLICY "Teachers can manage own quizzes" ON quizzes
  FOR ALL USING (
    teacher_id IN (SELECT id FROM teachers WHERE user_id = auth.uid())
  );

-- Policies for Submissions
CREATE POLICY "Students can insert own submissions" ON quiz_submissions
  FOR INSERT WITH CHECK (
    student_id IN (SELECT id FROM students WHERE user_id = auth.uid())
  );

CREATE POLICY "Students can view own submissions" ON quiz_submissions
  FOR SELECT USING (
    student_id IN (SELECT id FROM students WHERE user_id = auth.uid())
  );

CREATE POLICY "Teachers can view submissions for their quizzes" ON quiz_submissions
  FOR SELECT USING (
    quiz_id IN (
      SELECT id FROM quizzes 
      WHERE teacher_id IN (SELECT id FROM teachers WHERE user_id = auth.uid())
    )
  );
