-- Phase 2 Schema: Teaching & Learning Layer (Simplified - No RLS)
-- Apply RLS policies separately after tables are created

-- 1. Resources Table (LMS)
CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  type TEXT NOT NULL CHECK (type IN ('PDF', 'Video', 'Slides', 'Audio')),
  subject TEXT NOT NULL,
  grade INTEGER,
  url TEXT NOT NULL,
  thumbnail_url TEXT,
  language TEXT CHECK (language IN ('English', 'Hausa', 'Yoruba', 'Igbo')) DEFAULT 'English',
  curriculum_tags TEXT[],
  teacher_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_public BOOLEAN DEFAULT TRUE
);

-- 2. Quizzes Table
CREATE TABLE IF NOT EXISTS quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  subject TEXT NOT NULL,
  grade INTEGER,
  teacher_id BIGINT,
  duration_minutes INTEGER,
  is_published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Questions Table
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT,
  text TEXT NOT NULL,
  type TEXT CHECK (type IN ('MultipleChoice', 'Theory', 'TrueFalse')) NOT NULL,
  options JSONB,
  points INTEGER DEFAULT 1,
  image_url TEXT
);

-- 4. Quiz Submissions Table
CREATE TABLE IF NOT EXISTS quiz_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT,
  student_id BIGINT,
  answers JSONB,
  score INTEGER,
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT CHECK (status IN ('Graded', 'Pending')) DEFAULT 'Pending'
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_resources_teacher ON resources(teacher_id);
CREATE INDEX IF NOT EXISTS idx_resources_subject ON resources(subject);
CREATE INDEX IF NOT EXISTS idx_resources_grade ON resources(grade);

CREATE INDEX IF NOT EXISTS idx_quizzes_teacher ON quizzes(teacher_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_published ON quizzes(is_published);

CREATE INDEX IF NOT EXISTS idx_questions_quiz ON questions(quiz_id);

CREATE INDEX IF NOT EXISTS idx_submissions_quiz ON quiz_submissions(quiz_id);
CREATE INDEX IF NOT EXISTS idx_submissions_student ON quiz_submissions(student_id);
